### ISSUE TITLE
Route.post() Error running app with node

### ISSUE THREAD

**Issue by Madchatthew** [Madchatthew/udemy#1]
I get the following error when starting the app. I am on lesson 428. I have spent hours trying to figure out what is wrong and can't seem to find it. Any help would be appreciated.

Link to app - https://github.com/Madchatthew/udemy/tree/main/Modern%20Javascript%20Bootcamp/Part%202/ecomm

/ecomm/node_modules/express/lib/router/route.js:211
        throw new Error(msg);
        ^

Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.<computed> [as post] (/home/chad/Documents/ecomm/node_modules/express/lib/router/route.js:211:15)
    at proto.<computed> [as post] (/home/chad/Documents/ecomm/node_modules/express/lib/router/index.js:521:19)
    at Object.<anonymous> (/home/chad/Documents/ecomm/routes/admin/products.js:23:8)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/chad/Documents/ecomm/index.js:5:29)

Node.js v18.12.1

**Comment by Madchatthew** [comment]
Turned out the [requireTitle, requirePrice] wasn't defined in the validators middleware. Something must have happened during the back up process. I actually remember typing them in there at some point.
